INSERT INTO tbl_cards (hp, name, info, attack, dammage, weak, resis, retreat, CardsInCollection, fk_collection_id, fk_type_id, fk_stage_id)
VALUES
(90, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', NULL, '1', 1, 1, 1, 1),
(100, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', NULL, '2', 1, 1, 1, 2),
(120, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', NULL, '1', 1, 1, 1, 3),
(80, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', NULL, '1', 1, 1, 1, 1),
(90, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', NULL, '2', 1, 1, 1, 2),
(110, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', NULL, '2', 1, 1, 1, 3),
(70, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', NULL, '1', 1, 1, 6, 1),
(90, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '40', 'Grass', NULL, '2', 1, 1, 6, 2),
(100, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '20', 'Water', NULL, '1', 1, 1, 6, 1),
(120, 'Sandslash', 'Mouse Pokémon', 'Slash', '30', 'Water', NULL, '2', 1, 1, 6, 2),
(80, 'Clefairy', 'Fairy Pokémon', 'Sing', '—', 'Steel', 'Psychic', '1', 1, 1, 7, 1),
(100, 'Clefable', 'Fairy Pokémon', 'Metronome', '—', 'Steel', 'Psychic', '2', 1, 1, 7, 2),
(90, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', NULL, '1', 1, 1, 1, 1),
(100, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', NULL, '2', 1, 1, 1, 2),
(120, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', NULL, '3', 1, 1, 1, 3),
(90, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Attack', '20', 'Psychic', NULL, '1', 1, 1, 1, 1),
(110, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', NULL, '2', 1, 1, 1, 2),
(130, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', NULL, '3', 1, 1, 1, 3),
(100, 'Growlithe', 'Puppy Pokémon', 'Flame Tail', '20', 'Water', NULL, '1', 1, 1, 2, 1),
(120, 'Arcanine', 'Legendary Pokémon', 'Flamethrower', '50', 'Water', NULL, '3', 1, 1, 2, 2),
(80, 'Psyduck', 'Duck Pokémon', 'Headache', '—', 'Electric', NULL, '1', 1, 1, 3, 1),
(100, 'Golduck', 'Duck Pokémon', 'Confusion', '30', 'Electric', NULL, '2', 1, 1, 3, 2),
(90, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Electric', NULL, '1', 1, 1, 3, 1),
(110, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', '—', 'Electric', NULL, '2', 1, 1, 3, 2),
(120, 'Magmar', 'Spitfire Pokémon', 'Smokescreen', '10', 'Water', NULL, '2', 1, 1, 2, 1),
(130, 'Electabuzz', 'Electric Pokémon', 'Thunderpunch', '30+', 'Fighting', 'Steel', '2', 1, 1, 4, 1),
(140, 'Moltres', 'Flame Pokémon', 'Fire Blast', '70', 'Water', NULL, '3', 1, 1, 2, 1),
(140, 'Articuno', 'Freeze Pokémon', 'Ice Beam', '50', 'Steel', NULL, '3', 1, 1, 3, 1),
(150, 'Dragonair', 'Dragon Pokémon', 'Slam', '30x', 'Ice', NULL, '2', 1, 1, 7, 2),
(160, 'Dragonite', 'Dragon Pokémon', 'Hyper Beam', '50', 'Ice', NULL, '3', 1, 1, 7, 3);
